import type { Metadata } from "next"

import "./globals.css"
import Navbar from "@/components/Navbar"



export const metadata: Metadata = {
  title: "Three practice",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-[100vh]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
